webtalk_init -webtalk_dir /home/simo/Projects/Multidisciplinary_Project/CICERO/proj/regex_copro/regex_copro.sim/sim_1/behav/xsim/xsim.dir/AXI_top_tb_from_compiled_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 21 15:19:46 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e782b551-535a-43e0-867c-5d42b7995be0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ca222586bba94639ba2f5c6a74969b11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1280P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "29265 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "120392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1332430110 -regid "" -xml /home/simo/Projects/Multidisciplinary_Project/CICERO/proj/regex_copro/regex_copro.sim/sim_1/behav/xsim/xsim.dir/AXI_top_tb_from_compiled_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/simo/Projects/Multidisciplinary_Project/CICERO/proj/regex_copro/regex_copro.sim/sim_1/behav/xsim/xsim.dir/AXI_top_tb_from_compiled_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/simo/Projects/Multidisciplinary_Project/CICERO/proj/regex_copro/regex_copro.sim/sim_1/behav/xsim/xsim.dir/AXI_top_tb_from_compiled_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
