#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jul 21 15:26:25 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ca222586bba94639ba2f5c6a74969b11 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot AXI_top_tb_multiple_tests_from_csv_behav xil_defaultlib.AXI_top_tb_multiple_tests_from_csv xil_defaultlib.glbl -log elaborate.log"
xelab -wto ca222586bba94639ba2f5c6a74969b11 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot AXI_top_tb_multiple_tests_from_csv_behav xil_defaultlib.AXI_top_tb_multiple_tests_from_csv xil_defaultlib.glbl -log elaborate.log

