#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jul 21 15:26:26 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim AXI_top_tb_multiple_tests_from_csv_behav -key {Behavioral:sim_1:Functional:AXI_top_tb_multiple_tests_from_csv} -tclbatch AXI_top_tb_multiple_tests_from_csv.tcl -protoinst "protoinst_files/re2_copro.protoinst" -view /home/simo/Projects/Multidisciplinary_Project/CICERO/proj/regex_copro/AXI_top_tb_from_file_behav.wcfg -log simulate.log"
xsim AXI_top_tb_multiple_tests_from_csv_behav -key {Behavioral:sim_1:Functional:AXI_top_tb_multiple_tests_from_csv} -tclbatch AXI_top_tb_multiple_tests_from_csv.tcl -protoinst "protoinst_files/re2_copro.protoinst" -view /home/simo/Projects/Multidisciplinary_Project/CICERO/proj/regex_copro/AXI_top_tb_from_file_behav.wcfg -log simulate.log

